#SPDX-License-Identifier: MIT-0
---
# handlers file for ansible/roles/kafka
- name: reload pf
  ansible.builtin.command: pfctl -f /etc/pf.conf
# - name: validate kafka configuration in KAFKA jail
#   ansible.builtin.command: "bastille cmd {{ hls_jail.name }} nginx -t"
#   changed_when: false
#   listen: restart kafka in KAFKA jail

# - name: restart kafka in jail
#   ansible.builtin.command: "bastille service {{ hls_jail.name }} kafka restart"
#   listen: restart kafka in KAFKA jail
