#SPDX-License-Identifier: MIT-0
---
# defaults file for ansible/roles/postgres
packages:
  - bastille
  - tree
  - pftop

ext_if: eth0
bastille_interface: bastille0
bastille_release: "15.0-RELEASE"

jails:
  - name: postgres-server
    octet: "220"
    prefix: "10.17.89"
    subnet: "10.17.89.0/24"
    packages:
      - htop
      - tree
      - postgresql17-server
    daemons:
      - postgresql
    services:
      - postgresql
    ports:
      - port: 5432
        proto: tcp
    accounts:
      - name: spike
        uid: 1010
        gid: 1010
    new_groups:
      - name: spike
        gid: 1010

postgres_database: ldes
postgres_user: ldes

postgres_admin_password: "CHANGE_ME"
postgres_user_password: "CHANGE_ME"
